<?php

namespace Kunstmaan\AdminBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PageRepository extends EntityRepository
{
	public function getTopNode()
	{
	    $qb = $this->createQueryBuilder('b')
	               ->select('b')
                   ->where('b.parent is null')
	               ->addOrderBy('b.sequencenumber', 'DESC');

	    return $qb->getQuery()
	              ->getSingleResult();
	}
}