<?php

namespace Kunstmaan\DemoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * BlogRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExamplePageRepository extends EntityRepository
{

}