<?php

namespace Kunstmaan\AdminNodeBundle\Repository;

use Kunstmaan\AdminBundle\Entity\PageIFace;

use Doctrine\ORM\EntityRepository;

/**
 * NodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NodeRepository extends EntityRepository
{
	public function getTopNodes()
	{
	    $qb = $this->createQueryBuilder('b')
	               ->select('b')
                   ->where('b.parent is null')
	               ->addOrderBy('b.sequencenumber', 'DESC');

	    return $qb->getQuery()
	              ->getResult();
	}
	
	public function getNodeFor(PageIFace $page) {
        var_dump($page->getId());
        var_dump(get_class($page));
		return $this->findOneBy(array('refId' => $page->getId(), 'refEntityname' => get_class($page)));
	}
	
	public function getNodeForSlug($parentNode, $slug){
		if($parentNode){
			return $this->findOneBy(array('slug' => $slug, 'parent' => $parentNode->getId()));
		}
		return $this->findOneBy(array('slug' => $slug));
	}
}